config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :user_steps
  resources :after_register

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/after_register_controller.rb
class AfterRegisterController < ApplicationController
  include Wicked::Wizard

   steps :step_three, :step_four

   def show
     render_wizard
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  include Wicked::Wizard

   steps :step_one, :step_two

   def show
     render_wizard
   end
end

app/helpers/after_register_helper.rb
module AfterRegisterHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/views/after_register/step_four.html.erb
<%= render 'wizards/header', step: :step_four %>

<p>After register steps four</p>

<%= link_to 'Back', previous_wizard_path %>

app/views/after_register/step_three.html.erb
<%= render 'wizards/header', step: :step_three %>

<p>After register steps three</p>

<%= link_to 'Back', user_step_path(:step_two) %>
<%= link_to 'Next', next_wizard_path %>

app/views/home/index.html.erb
<%= render 'user_steps/one' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WickedWizard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_steps/_one.html.erb
<%= render 'wizards/header', step: :step_one %>

<p>User steps one</p>

<%= link_to 'Next', user_step_path(:step_two) %>

app/views/user_steps/step_one.html.erb
<%= render partial: 'user_steps/one' %>

app/views/user_steps/step_two.html.erb
<%= render 'wizards/header', step: :step_two%>

<p>User steps two</p>

<%= link_to 'Back', previous_wizard_path %>
<%= link_to 'Next', after_register_path(:step_three) %>

app/views/wizards/_header.html.erb
<ul id="wizards_header">
  <li class="<%= step == :step_one ? 'active' : '' %>">
    <%= link_to 'Step one', user_step_path(:step_one)%>
  </li>
  <li class="<%= step == :step_two ? 'active' : '' %>">
    <%= link_to 'Step two', user_step_path(:step_two)%>
  </li>
  <li class="<%= step == :step_three ? 'active' : '' %>">
    <%= link_to 'Step three', after_register_path(:step_three)%>
  </li>
  <li class="<%= step == :step_four ? 'active' : '' %>">
    <%= link_to 'Step four', after_register_path(:step_four)%>
  </li>
</ul>

<%= yield %>